

preload = /home/adi/.config/hypr/wallpapers/42271.jpg
wallpaper = eDP-1, /home/adi/.config/hypr/wallpapers/42271.jpg

splash=false
wallpaper {
    monitor = eDP-1
    path = /home/adi/.config/hypr/wallpapers/42271.jpg
    fit_mode = cover
}